import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { runInNewContext } from 'node:vm';
import * as accounts from '../src/lib/financeAccounts.ts';
import * as analysis from '../src/lib/financeAnalysis.ts';
const require = createRequire(import.meta.url), ts = require('typescript');
const compiled = ts.transpileModule(readFileSync(new URL('../src/components/FinanceAnalysisPanel.tsx', import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.React, target: ts.ScriptTarget.ES2022 } }).outputText;
const aid = 'a'.repeat(24), fid = 'b'.repeat(24), rid = 'c'.repeat(32), sha = 'd'.repeat(64), at = '2026-09-19T01:00:00Z';
const query = { start: '2026-01-01', end: '2026-09-18', baseCurrency: 'CNY', step: 'month', accountIds: 'all' };
const account = () => ({ id: aid, owner: 'member1', name: 'PRIVATE ACCOUNT', institution: 'PRIVATE BANK', kind: 'asset', currency: 'CNY', note: '', archived: false, revision: 1, createdAt: at, updatedAt: at, visibility: 'private' });
const profile = () => ({ accountId: aid, revision: 0, updatedAt: null, assetClass: 'unknown', liquidity: 'unknown' });
const coverage = () => ({ selectedCount: 1, knownValuationCount: 1, convertedCount: 1, missingValuationCount: 0, unknownValuationCount: 0, olderValuationCount: 0, missingFxCount: 0 });
const summary = () => ({ knownAssetCents: '11000', knownLiabilityCents: '0', knownNetCents: '11000', complete: true, coverage: coverage() });
const point = date => ({ date, valuation: { asOf: date, amountCents: 11000, source: 'manual', updatedAt: at }, convertedCents: '11000', fx: { sourceCurrency: 'CNY', targetCurrency: 'CNY', sourcePerEur: '1', targetPerEur: '1', rateDate: null, ageDays: 0, method: 'identity', observations: [] } });
const review = () => ({ revision: 0, contextDigest: sha, status: 'unreviewed', confirmedAt: null, cashflowCount: 0, recordedNetFlowCents: '0', canConfirm: true });
const change = () => ({ originalChangeCents: '0', recordedNetFlowCents: '0', valuationResidualCents: null, convertedChangeCents: '0', convertedNetFlowCents: null, convertedValuationResidualCents: null, fxEffectCents: null, roundingCents: null, status: 'unreviewed' });
const report = (q = query) => ({ owner: 'member1', scope: 'private_accounts_only', ...q, accountIds: [aid], accounts: [{ account: account(), profile: profile(), opening: point(q.start), closing: point(q.end), review: review(), change: change() }], summary: summary(), series: [{ date: q.start, summary: summary() }, { date: q.end, summary: summary() }], allocation: [{ key: 'unknown', knownCents: '11000', count: 1 }], liquidity: [{ key: 'unknown', knownCents: '11000', count: 1 }], change: { convertedChangeCents: '0', convertedNetFlowCents: null, convertedValuationResidualCents: null, fxEffectCents: null, roundingCents: null, complete: false, reviewedCount: 0 } });
const flow = () => ({ id: fid, accountId: aid, date: '2026-09-18', direction: 'in', amountCents: 1000, note: 'PRIVATE FLOW', revision: 1, createdAt: at, updatedAt: at });
const clone = value => structuredClone(value);
// Generated from finance_fx.py 5e121f1: synthetic CSV -> parse_ecb_csv -> SQLite save/load -> resolve_fx_quote.
// These are actual quote DTOs and canonical endpoint URLs, with computed version/body hashes and UTC timestamps.
const actualFxQuotes = {"2026-09-01":{"sourceCurrency":"USD","targetCurrency":"CNY","sourcePerEur":"1.17","targetPerEur":"8.3","rateDate":"2026-09-01","ageDays":0,"method":"ecb_cross","observations":[{"date":"2026-09-01","currency":"USD","unitsPerEur":"1.17","version":"3382ecd554fefd3a171742540c328f06891a28c776359f98f565fdfb89e54588","sourceUrl":"https://data-api.ecb.europa.eu/service/data/EXR/D..EUR.SP00.A?startPeriod=2026-09-01&endPeriod=2026-09-18&format=csvdata","bodySha256":"d60e8aea1ba9465932a3ddd0d92eb6d9cf96c974cea7d55e1f4ff282d62752bc","fetchedAt":"2026-09-19T01:00:00.000000+00:00","lastCheckedAt":"2026-09-19T01:00:00.000000+00:00"},{"date":"2026-09-01","currency":"CNY","unitsPerEur":"8.3","version":"67409567cf76f85103715093936511c3d94511e2100e1302aa3c774af3952489","sourceUrl":"https://data-api.ecb.europa.eu/service/data/EXR/D..EUR.SP00.A?startPeriod=2026-09-01&endPeriod=2026-09-18&format=csvdata","bodySha256":"d60e8aea1ba9465932a3ddd0d92eb6d9cf96c974cea7d55e1f4ff282d62752bc","fetchedAt":"2026-09-19T01:00:00.000000+00:00","lastCheckedAt":"2026-09-19T01:00:00.000000+00:00"}]},"2026-09-18":{"sourceCurrency":"USD","targetCurrency":"CNY","sourcePerEur":"1.18","targetPerEur":"8.4","rateDate":"2026-09-18","ageDays":0,"method":"ecb_cross","observations":[{"date":"2026-09-18","currency":"USD","unitsPerEur":"1.18","version":"a1c46c82034b026963e645cb7858e25d386123263510d367dfdb64031f5ad1db","sourceUrl":"https://data-api.ecb.europa.eu/service/data/EXR/D..EUR.SP00.A?startPeriod=2026-09-01&endPeriod=2026-09-18&format=csvdata","bodySha256":"d60e8aea1ba9465932a3ddd0d92eb6d9cf96c974cea7d55e1f4ff282d62752bc","fetchedAt":"2026-09-19T01:00:00.000000+00:00","lastCheckedAt":"2026-09-19T01:00:00.000000+00:00"},{"date":"2026-09-18","currency":"CNY","unitsPerEur":"8.4","version":"a635833140f3ddeadd6cd4004a68dd7e9c10ab7acc3c177078c1a40ff8bab3b3","sourceUrl":"https://data-api.ecb.europa.eu/service/data/EXR/D..EUR.SP00.A?startPeriod=2026-09-01&endPeriod=2026-09-18&format=csvdata","bodySha256":"d60e8aea1ba9465932a3ddd0d92eb6d9cf96c974cea7d55e1f4ff282d62752bc","fetchedAt":"2026-09-19T01:00:00.000000+00:00","lastCheckedAt":"2026-09-19T01:00:00.000000+00:00"}]}};
function withActualFx(raw) { raw.accounts[0].account.currency = 'USD'; for (const p of [raw.accounts[0].opening, raw.accounts[0].closing]) { p.fx = clone(actualFxQuotes[p.date]); p.convertedCents = p.date === '2026-09-01' ? '78034' : '78305'; } raw.summary = { ...raw.summary, knownAssetCents: '78305', knownNetCents: '78305' }; raw.series = raw.series.map(p => ({ ...p, summary: { ...p.summary, knownAssetCents: p.date === '2026-09-01' ? '78034' : '78305', knownNetCents: p.date === '2026-09-01' ? '78034' : '78305' } })); raw.allocation[0].knownCents = raw.liquidity[0].knownCents = '78305'; return raw; }


test('report binds owner, scope, requested account set, dates and classifications', () => {
  const raw = report(); raw.secretToken = 'ignored'; assert(!('secretToken' in analysis.readAnalysisReport(raw, 'member1', query)));
  for (const patch of [{ owner: 'other' }, { scope: 'shared' }, { end: '2026-09-17' }, { accountIds: [aid, aid] }, { baseCurrency: 'USD' }]) assert.throws(() => analysis.readAnalysisReport({ ...raw, ...patch }, 'member1', query));
  assert.throws(() => analysis.readAnalysisReport(raw, 'member1', { ...query, accountIds: ['f'.repeat(24)] }));
  raw.accounts[0].account.owner = 'other'; assert.throws(() => analysis.readAnalysisReport(raw, 'member1', query));
});
test('unknown and missing original valuations remain null with honest incomplete coverage', () => {
  const raw = report(), s = { knownAssetCents: '0', knownLiabilityCents: '0', knownNetCents: '0', complete: false, coverage: { ...coverage(), knownValuationCount: 0, convertedCount: 0, unknownValuationCount: 1 } };
  raw.accounts[0].closing.valuation.amountCents = null; raw.accounts[0].closing.convertedCents = null; raw.summary = s; raw.series[1].summary = s; raw.allocation[0].knownCents = '0'; raw.liquidity[0].knownCents = '0';
  const parsed = analysis.readAnalysisReport(raw, 'member1', query); assert.equal(parsed.accounts[0].closing.valuation.amountCents, null); assert.equal(analysis.analysisMoney(null, 'CNY'), '未能计算'); assert.match(analysis.coverageText(parsed.summary.coverage), /金额未知 1/);
  raw.accounts[0].closing.convertedCents = '0'; assert.throws(() => analysis.readAnalysisReport(raw, 'member1', query));
});
test('actual persisted ECB quote DTO accepts canonical data-api endpoint and rejects altered provenance', () => {
  const q = { ...query, start: '2026-09-01' }, raw = withActualFx(report(q));
  assert.equal(analysis.readAnalysisReport(raw, 'member1', q).accounts[0].closing.fx.observations[0].version, actualFxQuotes[q.end].observations[0].version);
  const source = actualFxQuotes[q.end].observations[0].sourceUrl;
  for (const url of [source.replace('data-api.ecb.europa.eu', 'ecb.europa.eu.evil.example'), source.replace('/D..EUR.SP00.A?', '/D..USD.SP00.A?'), source + '&extra=1', source.replace('format=csvdata', 'format=jsondata'), source.replace('startPeriod=2026-09-01', 'startPeriod=2026-09-19'), source.replace('https:', 'http:'), 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml']) { const bad = clone(raw); bad.accounts[0].closing.fx.observations[0].sourceUrl = url; assert.throws(() => analysis.readAnalysisReport(bad, 'member1', q), url); }
  const badDate = clone(raw); badDate.accounts[0].opening.fx.observations[0].date = '2026-09-02'; assert.throws(() => analysis.readAnalysisReport(badDate, 'member1', q));
  raw.accounts[0].closing.fx.observations[0].version = 1; assert.throws(() => analysis.readAnalysisReport(raw, 'member1', q));
});
test('precise formatting, known-asset percentages and inclusive period limit avoid numeric loss', () => {
  assert.equal(analysis.analysisMoney('30000000000000001', 'CNY'), 'CNY 300,000,000,000,000.01');
  assert.equal(analysis.analysisShare('1', '3'), '33.3%'); assert.equal(analysis.analysisShare('0', '0'), '比例不可用'); assert.equal(analysis.analysisShare('1', '-1'), '比例不可用');
  assert.throws(() => analysis.analysisQuery({ ...query, start: '2025-01-01', end: '2026-01-02' }));
  assert.throws(() => analysis.analysisQuery({ ...query, start: '2026-02-30' })); assert.throws(() => analysis.analysisQuery({ ...query, accountIds: [] }));
});
test('trend breaks at partial or old valuation points and preserves known zero and negative amounts', () => {
  const raw = [{ date: '2026-01-01', summary: { ...summary(), knownNetCents: '-500' } }, { date: '2026-01-02', summary: { ...summary(), complete: false } }, { date: '2026-01-03', summary: { ...summary(), knownNetCents: '0' } }, { date: '2026-01-04', summary: { ...summary(), knownNetCents: '500' } }];
  const trend = analysis.analysisTrend(raw); assert.equal(trend.gapCount, 1); assert.equal(trend.points[1].y, null); assert.equal(trend.points[2].y, .5); assert.equal(trend.min, '-500'); assert.equal(trend.max, '500'); assert.equal(trend.segments.length, 1); assert.equal(trend.segments[0].from.date, '2026-01-03');
  assert.equal(analysis.analysisTrend([{ date: '2026-01-01', summary: { ...summary(), complete: false } }]).min, null);
});
test('write intents bind account/event/CAS and require explicit interval confirmation', () => {
  const draft = { date: query.end, direction: 'out', amount: '123.45', note: 'synthetic' }, intent = analysis.cashflowIntent(account(), draft, flow(), rid);
  assert.equal(intent.method, 'PATCH'); assert.equal(intent.body.amountCents, 12345); assert.equal(intent.body.revision, 1); assert(Object.isFrozen(intent.body));
  assert.throws(() => analysis.cashflowIntent({ ...account(), archived: true }, draft, null, rid)); assert.throws(() => analysis.cashflowIntent(account(), draft, { ...flow(), accountId: 'e'.repeat(24) }, rid));
  assert.throws(() => analysis.reviewIntent(report().accounts[0], query, false, rid));
  assert.equal(analysis.reviewIntent(report().accounts[0], query, true, rid).body.contextDigest, sha);
  assert.equal(analysis.deleteCashflowIntent(account(), flow(), rid).method, 'DELETE'); assert.equal(analysis.profileIntent(profile(), { assetClass: 'cash', liquidity: 'immediate' }, rid).body.revision, 0);
  assert.deepEqual(Object.keys(analysis.refreshRatesIntent(query, rid).body).sort(), ['end', 'requestId', 'start']);
});
test('uncertain operations keep original IDs and rejection after uncertainty never unlocks', () => {
  const intent = analysis.refreshRatesIntent(query, rid), rejected = new accounts.AccountRejected('conflict', 409);
  assert.equal(analysis.failedAnalysisIntent(intent, rejected), null); assert.equal(analysis.failedAnalysisIntent({ ...intent, uncertain: true }, rejected).requestId, rid);
  assert.equal(analysis.readAnalysisOperation({ requestId: rid, found: false, receipt: null }, rid), null);
  assert.throws(() => analysis.readAnalysisOperation({ requestId: 'e'.repeat(32), found: false, receipt: null }, rid));
});

// Executes production TSX with hook/Paper and transport doubles. Real browser and Flask tests are separate.
function harness() {
  const f = { session: { user: { role: 'member', id: 'member1', householdId: 'home1', auth_version: 1 }, csrf: 'synthetic-csrf' }, calls: [], prof: profile(), review: review(), flows: [], receipt: null, lost: false, conflict: false, reportFailure: false, gate: null, useFx: false, archived: false };
  const slots = [], effects = [], cleanups = [], lifecycle = new Map(); let cursor = 0, dirty = true, tree, closed = false, pending = false, exited = false;
  const document = { hidden: false, addEventListener: (k, fn) => lifecycle.set(k, fn), removeEventListener: k => lifecycle.delete(k) }, window = { addEventListener: (k, fn) => lifecycle.set(k, fn), removeEventListener: k => lifecycle.delete(k) };
  const useState = initial => { const i = cursor++; if (!(i in slots)) slots[i] = typeof initial === 'function' ? initial() : initial; return [slots[i], v => { slots[i] = typeof v === 'function' ? v(slots[i]) : v; dirty = true; }]; }, useRef = initial => { const i = cursor++; if (!(i in slots)) slots[i] = { current: initial }; return slots[i]; }, changed = (a, b) => !a || !b || a.length !== b.length || a.some((v, i) => v !== b[i]);
  const useEffect = (fn, deps) => { const i = cursor++; if (changed(slots[i], deps)) { slots[i] = deps; effects.push(() => { cleanups[i]?.(); cleanups[i] = fn(); }); } }, useCallback = (fn, deps) => { const i = cursor++; if (!slots[i] || changed(slots[i].deps, deps)) slots[i] = { deps, fn }; return slots[i].fn; };
  const react = { useState, useRef, useEffect, useCallback, Fragment: 'Fragment', createElement: (type, props, ...children) => ({ type, props: { ...props, children: children.flat(Infinity).filter(v => v !== undefined) } }) };
  const household = { user: f.session.user, online: true, identityKey: accounts.accountSignature(f.session), refresh: async () => {} };
  async function request(path, _signal, options = {}) {
    f.calls.push({ path, method: options.method || 'GET', body: clone(options.payload || null), csrf: options.csrf });
    if (path === '/me') return clone(f.session);
    const url = new URL('https://local' + path), q = Object.fromEntries(url.searchParams);
    if (path.startsWith('/finance-accounts?')) return { owner: 'member1', asOf: q.asOf, status: 'all', scope: 'manual_accounts_only', accounts: [{ ...account(), archived: f.archived, valuation: point(q.asOf).valuation }], totals: [{ currency: 'CNY', assetCount: 1, liabilityCount: 0, knownCount: 1, unknownCount: 0, missingCount: 0, olderCount: 0, knownAssetCents: '11000', knownLiabilityCents: '0', knownNetCents: '11000' }] };
    if (path.startsWith('/finance-analysis/report?')) { if (f.gate) await f.gate; if (f.reportFailure) throw new accounts.AccountError('synthetic read failed', 503); const raw = report({ ...q, accountIds: 'all' }); if (f.useFx) withActualFx(raw); raw.accounts[0].account.archived = f.archived; raw.accounts[0].profile = clone(f.prof); raw.accounts[0].review = { ...clone(f.review), cashflowCount: f.flows.length }; return raw; }
    if (path.includes('/operations/')) return { requestId: path.split('/').at(-1), found: !!f.receipt, receipt: f.receipt ? { ...clone(f.receipt), replayed: true } : null };
    if ((!options.method || options.method === 'GET') && path.includes('/cashflows?')) return { owner: 'member1', accountId: aid, start: q.start, end: q.end, items: clone(f.flows.slice((Number(q.page) - 1) * 50, Number(q.page) * 50)), page: Number(q.page), pageSize: 50, total: f.flows.length };
    if (options.method) {
      if (f.conflict) { f.conflict = false; f.prof.revision++; throw new accounts.AccountError('revision changed', 409, 'revision_conflict'); }
      let operation, result; const body = options.payload;
      if (path.endsWith('/profile')) { operation = 'profile'; f.prof = { ...f.prof, assetClass: body.assetClass, liquidity: body.liquidity, revision: f.prof.revision + 1, updatedAt: at }; result = f.prof; }
      else if (path.includes('/reviews/')) { operation = 'review'; f.review = { ...f.review, revision: f.review.revision + 1, status: 'current', confirmedAt: at }; result = f.review; }
      else if (path.endsWith('/rates/refresh')) { operation = 'rates_refresh'; result = { inserted: 1, updated: 0, rateCount: 2, retrievedAt: at }; }
      else if (options.method === 'DELETE') { operation = 'cashflow_delete'; const deletedId = path.split('/').at(-1); f.flows = f.flows.filter(f => f.id !== deletedId); result = { deleted: true, id: deletedId }; }
      else { operation = options.method === 'POST' ? 'cashflow_create' : 'cashflow_update'; result = { ...flow(), ...body, id: fid, accountId: aid, revision: 1 }; delete result.requestId; f.flows = [result]; }
      f.receipt = { requestId: body.requestId, operation, accountId: operation === 'rates_refresh' ? null : aid, completedAt: at, result: clone(result), replayed: false };
      if (f.lost) throw new accounts.AccountError('lost response'); return clone(f.receipt);
    }
    throw Error('Unexpected path ' + path);
  }
  const modules = { react, 'react-native': { AppState: { currentState: 'active', addEventListener: (_k, fn) => { lifecycle.set('app', fn); return { remove() {} }; } }, Platform: { OS: 'web' }, StyleSheet: { create: v => v }, View: 'View' }, 'expo-router': { useFocusEffect: fn => useEffect(fn, [fn]) }, 'react-native-paper': { ...Object.fromEntries(['ActivityIndicator', 'Button', 'Divider', 'Text', 'TextInput'].map(k => [k, k])), useTheme: () => ({ colors: { error: 'red' } }) }, '../lib/household': { useHousehold: () => household }, '../lib/financeAccounts': { ...accounts, accountRequest: request }, '../lib/financeAnalysis': { ...analysis, analysisRequest: request }, '../ui/components': { EmptyState: 'EmptyState', PageHeader: 'PageHeader', SectionCard: 'SectionCard' }, '../ui/SelectionRow': { SelectionRow: 'SelectionRow' }, '../ui/theme': { useDisplayDensity: () => ({ sectionGap: 12, screenGap: 20 }) } };
  const exports = {}; runInNewContext(compiled, { exports, require: name => { assert(name in modules, name); return modules[name]; }, document, window, navigator: { onLine: true }, AbortController, Intl, Date, console });
  const props = { onBack: () => { exited = true; }, onPendingChange: v => { pending = v; } };
  function expand(node) { if (!node || typeof node !== 'object') return node; if (typeof node.type === 'function') return expand(node.type(node.props)); return { ...node, props: { ...node.props, ...(node.props.action ? { action: expand(node.props.action) } : {}), children: (node.props.children || []).map(expand) } }; }
  function render() { cursor = 0; dirty = false; tree = expand(exports.default(props)); for (const effect of effects.splice(0)) effect(); }
  async function settle() { for (let i = 0; i < 24; ++i) { if (dirty && !closed) render(); await new Promise(resolve => setImmediate(resolve)); } }
  const nodes = (node = tree) => !node || typeof node !== 'object' ? [] : [node, ...(node.props.action ? nodes(node.props.action) : []), ...node.props.children.flatMap(nodes)];
  const text = (node = tree) => typeof node === 'string' || typeof node === 'number' ? String(node) : node && typeof node === 'object' ? [node.props.title || '', node.props.description || '', ...(node.props.children || []).map(text)].join(' ') : '';
  const control = label => nodes().find(n => ['Button', 'SelectionRow', 'TextInput'].includes(n.type) && (n.props.label === label || n.props.accessibilityLabel === label || text(n).trim().replace(/\s+/g, ' ') === label));
  async function click(label) { const n = control(label); assert(n, 'Missing: ' + label + '\n' + text()); assert(!n.props.disabled, 'Disabled: ' + label); n.props.onPress(); await settle(); }
  async function input(label, value) { const n = control(label); assert(n, label); assert(!n.props.disabled, label); n.props.onChangeText(value); await settle(); }
  return { f, household, settle, click, input, control, text, writes: () => f.calls.filter(c => c.method !== 'GET'), get pending() { return pending; }, get exited() { return exited; }, async hide() { document.hidden = true; lifecycle.get('visibilitychange')(); await settle(); }, async show() { document.hidden = false; lifecycle.get('visibilitychange')(); await settle(); }, close() { closed = true; cleanups.forEach(c => c?.()); } };
}
const confirm = '我已核对以上内容，确认执行本次操作';
test('panel loads cached report, shows private coverage and never refreshes network implicitly', async t => { const h = harness(); t.after(h.close); await h.settle(); assert.match(h.text(), /PRIVATE ACCOUNT/); assert.match(h.text(), /不能直接视为交易收益/); assert.equal(h.writes().length, 0); await h.click('重新读取当前分析'); assert.equal(h.writes().length, 0); });
test('zero flow records require a separate explicit exact-period confirmation', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('核对 PRIVATE ACCOUNT'); assert.match(h.text(), /尚不能据此认定/); await h.click('核对区间完整性'); assert(h.control('确认此区间完整').props.disabled); assert.equal(h.writes().length, 0); await h.click('我已核对两端估值及该区间全部外部资金进出，确认记录完整'); await h.click('确认此区间完整'); assert.equal(h.writes().length, 1); assert(h.writes()[0].path.includes('/reviews/')); assert.equal(h.writes()[0].body.confirmed, true); assert.equal(h.writes()[0].csrf, 'synthetic-csrf'); });
test('cashflow saves preserve integer original cents and deletion needs explicit acknowledgment', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('核对 PRIVATE ACCOUNT'); await h.click('登记资金进出'); await h.input('原币金额（最多两位小数）', '123.45'); await h.input('本人备注', 'synthetic'); await h.click('保存'); assert.equal(h.writes()[0].body.amountCents, 12345); assert.equal(h.writes()[0].body.revision, 0); await h.click('修改此笔资金'); await h.input('原币金额（最多两位小数）', '120.00'); await h.click('保存'); assert.equal(h.writes()[1].method, 'PATCH'); assert.equal(h.writes()[1].body.revision, 1); await h.click('删除此笔资金'); assert(h.control('确认删除资金进出').props.disabled); await h.click(confirm); await h.click('确认删除资金进出'); assert.equal(h.writes()[2].method, 'DELETE'); assert.deepEqual(Object.keys(h.writes()[2].body).sort(), ['requestId', 'revision']); });
test('lost write reply recovers exact receipt with no duplicate write', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('核对 PRIVATE ACCOUNT'); await h.click('编辑分类与流动性'); await h.click('现金'); h.f.lost = true; await h.click('保存'); const original = h.writes()[0].body.requestId; assert(h.pending); assert.match(h.text(), new RegExp(original)); await h.click('查询原操作结果'); assert.equal(h.writes().length, 1); assert.equal(h.pending, false); assert.match(h.text(), /原操作已确认保存/); });
test('CAS rejection preserves draft and requires refreshed explicit version adoption', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('核对 PRIVATE ACCOUNT'); await h.click('编辑分类与流动性'); await h.click('现金'); h.f.conflict = true; await h.click('保存'); assert(h.control('保存').props.disabled); await h.click('重新读取当前分析'); await h.click('采用当前版本，保留填写内容'); await h.click('保存'); assert.equal(h.writes()[1].body.assetClass, 'cash'); assert.equal(h.writes()[1].body.revision, 1); assert.notEqual(h.writes()[1].body.requestId, h.writes()[0].body.requestId); });
test('official refresh is explicit and sends no private account or amount fields', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('更新官方参考汇率'); assert.equal(h.writes().length, 0); await h.click('确认更新汇率'); assert.equal(h.writes().length, 1); assert.equal(h.writes()[0].path, '/finance-analysis/rates/refresh'); assert.deepEqual(Object.keys(h.writes()[0].body).sort(), ['end', 'requestId', 'start']); });
test('background conceals private content and invalidates late responses before resume reread', async t => { const h = harness(); t.after(h.close); await h.settle(); let release; h.f.gate = new Promise(resolve => { release = resolve; }); const refresh = h.click('重新读取当前分析'); await h.settle(); await h.hide(); release(); await refresh; await h.settle(); assert(!h.text().includes('PRIVATE ACCOUNT')); h.f.gate = null; await h.show(); assert(h.text().includes('PRIVATE ACCOUNT')); });
test('changed session after a read clears private data and blocks mutations', async t => { const h = harness(); t.after(h.close); await h.settle(); let release; h.f.gate = new Promise(resolve => { release = resolve; }); const refresh = h.click('重新读取当前分析'); await h.settle(); h.f.session.user.auth_version++; release(); await refresh; await h.settle(); assert(!h.text().includes('PRIVATE ACCOUNT')); assert(!h.control('更新官方参考汇率'), h.text()); assert.match(h.text(), /身份或权限已变化/); });
test('confirmed write followed by failed reload stays confirmed and never offers retry write', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('更新官方参考汇率'); h.f.reportFailure = true; await h.click('确认更新汇率'); assert.match(h.text(), /原操作已确认保存/); assert(!h.control('按原请求重试')); assert.equal(h.pending, false); h.f.reportFailure = false; await h.click('重新读取当前分析'); assert.equal(h.writes().length, 1); });
test('unknown operation not found stays blocked until fresh read and explicit end acknowledgment', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('查询以前的操作'); await h.input('分析操作编号', rid); await h.click('使用此操作编号'); await h.click('查询原操作结果'); assert(h.pending); assert(h.control('结束本次核对，保留编号').props.disabled); await h.click('我已核对当前资料，理解原请求仍可能完成，决定结束本次核对'); await h.click('结束本次核对，保留编号'); assert.equal(h.pending, false); assert.equal(h.writes().length, 0); assert.equal(h.control('分析操作编号').props.value, rid); });
test('overview hides advanced inputs and operation recovery until asked and supports date presets', async t => { const h = harness(); t.after(h.close); await h.settle(); assert(!h.control('起点 YYYY-MM-DD')); assert(!h.control('分析操作编号')); await h.click('今年'); const path = h.f.calls.filter(c => c.path.startsWith('/finance-analysis/report?')).at(-1).path; assert.match(path, /start=\d{4}-01-01/); await h.click('自定义范围'); assert(h.control('起点 YYYY-MM-DD')); assert(h.control('报告币种（如 CNY）')); await h.click('查看取样明细与覆盖'); assert.match(h.text(), /已选 1/); });
test('transport restricts routes, sends DELETE JSON + CSRF and does not echo untrusted authentication bodies', async t => {
  const original = globalThis.fetch, calls = []; t.after(() => { globalThis.fetch = original; });
  globalThis.fetch = async (url, init) => { calls.push({ url, init }); return new Response(JSON.stringify({ ok: true }), { headers: { 'Content-Type': 'application/json' } }); };
  const signal = new AbortController().signal, intent = analysis.deleteCashflowIntent(account(), flow(), rid);
  await analysis.analysisRequest(intent.path, signal, { method: intent.method, payload: intent.body, csrf: 'test' }); assert.equal(calls[0].init.cache, 'no-store'); assert.equal(calls[0].init.redirect, 'error'); assert.equal(calls[0].init.headers['X-CSRF-Token'], 'test'); assert.equal(calls[0].init.method, 'DELETE');
  await assert.rejects(analysis.analysisRequest('https://evil.example/', signal)); assert.equal(calls.length, 1);
  globalThis.fetch = async () => new Response('PRIVATE SERVER BODY', { status: 403 }); await assert.rejects(analysis.analysisRequest(analysis.analysisReportPath(query), signal), error => error.status === 403 && !error.message.includes('PRIVATE SERVER BODY'));
});

test('real panel renders actual cached data-api quotes and reveals provenance only on demand', async t => { const h = harness(); t.after(h.close); await h.settle(); await h.click('自定义范围'); await h.input('起点 YYYY-MM-DD', '2026-09-01'); await h.input('终点 YYYY-MM-DD', '2026-09-18'); h.f.useFx = true; await h.click('读取所选范围'); assert.match(h.text(), /CNY 783.05/); assert(!h.text().includes('data-api.ecb.europa.eu')); await h.click('核对 PRIVATE ACCOUNT'); assert.match(h.text(), /USD 110.00/); await h.click('查看汇率来源与日期'); assert(h.text().includes(actualFxQuotes['2026-09-18'].observations[0].sourceUrl)); assert(h.text().includes(actualFxQuotes['2026-09-18'].observations[0].version)); assert.equal(h.writes().length, 0); });
test('archived account remains readable and reviewable but profile and cashflow mutations stay disabled', async t => { const h = harness(); t.after(h.close); h.f.archived = true; await h.settle(); await h.click('核对 PRIVATE ACCOUNT'); assert(h.control('编辑分类与流动性').props.disabled); assert(h.control('登记资金进出').props.disabled); assert(!h.control('核对区间完整性').props.disabled); assert.match(h.text(), /恢复后可编辑分类与资金进出/); assert.equal(h.writes().length, 0); });

test('deleting the only final-page cashflow reloads page one instead of leaving an empty out-of-range page', async t => { const h = harness(); t.after(h.close); h.f.flows = Array.from({ length: 51 }, (_, i) => ({ ...flow(), id: (i + 1).toString(16).padStart(24, '0'), note: 'synthetic entry ' + (i + 1) })); await h.settle(); await h.click('核对 PRIVATE ACCOUNT'); await h.click('下一页'); assert.match(h.text(), /synthetic entry 51/); await h.click('删除此笔资金'); await h.click(confirm); await h.click('确认删除资金进出'); assert.equal(h.f.flows.length, 50); assert.match(h.text(), /synthetic entry 1/); assert(!h.text().includes('synthetic entry 51')); assert(h.control('上一页').props.disabled); assert(h.control('下一页').props.disabled); });
