import { AccountDiscarded, AccountError, AccountRejected, accountDay, newAccountRequestId, parseAccountAmount, readAccount, readAccountValuation, type FinanceAccount, type AccountValuation } from './financeAccounts.ts';

export const assetClasses = { unknown: '未分类', cash: '现金', fixed_income: '固定收益', equity: '股票', fund: '基金', property: '房产', other: '其他' } as const;
export const liquidityClasses = { unknown: '尚未核对', immediate: '可即时使用', within_month: '一个月内可用', over_month: '超过一个月', restricted: '受限' } as const;
export type Profile = { accountId: string; revision: number; updatedAt: string | null; assetClass: keyof typeof assetClasses; liquidity: keyof typeof liquidityClasses };
export type AnalysisQuery = { start: string; end: string; baseCurrency: string; step: 'day' | 'month'; accountIds: 'all' | string[] };
export type Coverage = { selectedCount: number; knownValuationCount: number; convertedCount: number; missingValuationCount: number; unknownValuationCount: number; olderValuationCount: number; missingFxCount: number };
export type Summary = { knownAssetCents: string; knownLiabilityCents: string; knownNetCents: string; complete: boolean; coverage: Coverage };
export type FxQuote = { sourceCurrency: string; targetCurrency: string; sourcePerEur: string; targetPerEur: string; rateDate: string | null; ageDays: number; method: 'identity' | 'ecb_cross'; observations: { date: string; currency: string; unitsPerEur: string; version: string; sourceUrl: string; bodySha256: string; fetchedAt: string; lastCheckedAt: string }[] };
export type Point = { date: string; valuation: AccountValuation | null; convertedCents: string | null; fx: FxQuote | null };
export type Review = { revision: number; contextDigest: string; status: 'unreviewed' | 'current' | 'stale'; confirmedAt: string | null; cashflowCount: number; recordedNetFlowCents: string; canConfirm: boolean };
export type Change = { originalChangeCents: string | null; recordedNetFlowCents: string; valuationResidualCents: string | null; convertedChangeCents: string | null; convertedNetFlowCents: string | null; convertedValuationResidualCents: string | null; fxEffectCents: string | null; roundingCents: string | null; status: 'unreviewed' | 'stale' | 'missing_valuations' | 'missing_fx' | 'complete' };
export type AnalysisAccount = { account: FinanceAccount; profile: Profile; opening: Point; closing: Point; review: Review; change: Change };
export type AnalysisReport = { owner: string; scope: 'private_accounts_only'; start: string; end: string; baseCurrency: string; step: 'day' | 'month'; accountIds: string[]; accounts: AnalysisAccount[]; summary: Summary; series: { date: string; summary: Summary }[]; allocation: { key: Profile['assetClass']; knownCents: string; count: number }[]; liquidity: { key: Profile['liquidity']; knownCents: string; count: number }[]; change: { convertedChangeCents: string | null; convertedNetFlowCents: string | null; convertedValuationResidualCents: string | null; fxEffectCents: string | null; roundingCents: string | null; complete: boolean; reviewedCount: number } };
export type Cashflow = { id: string; accountId: string; date: string; direction: 'in' | 'out'; amountCents: number; note: string; revision: number; createdAt: string; updatedAt: string };
export type Cashflows = { owner: string; accountId: string; start: string; end: string; items: Cashflow[]; page: number; pageSize: number; total: number };
export type FlowDraft = { date: string; direction: 'in' | 'out'; amount: string; note: string };
export type AnalysisReceipt = { requestId: string; operation: 'profile' | 'cashflow_create' | 'cashflow_update' | 'cashflow_delete' | 'review' | 'rates_refresh'; accountId: string | null; completedAt: string; result: Profile | Cashflow | Review | { deleted: true; id: string } | { inserted: number; updated: number; rateCount: number; retrievedAt: string }; replayed: boolean };
export type AnalysisIntent = { requestId: string; operation: AnalysisReceipt['operation']; accountId: string | null; method: 'POST' | 'PATCH' | 'PUT' | 'DELETE'; path: string; body: Readonly<Record<string, unknown>>; uncertain: boolean };
const bad = (): never => { throw new AccountError('分析资料无法完整核对，请重新读取。'); };
const obj = (v: unknown): Record<string, unknown> => v !== null && typeof v === 'object' && !Array.isArray(v) ? v as Record<string, unknown> : bad();
const str = (v: unknown, max = 2000): string => typeof v === 'string' && v.length <= max && !/[\u0000-\u0008\u000b-\u001f\u007f]/.test(v) ? v : bad();
const int = (v: unknown, min = 0, max = Number.MAX_SAFE_INTEGER): number => typeof v === 'number' && Number.isSafeInteger(v) && v >= min && v <= max ? v : bad();
const bool = (v: unknown): boolean => typeof v === 'boolean' ? v : bad();
const array = (v: unknown, max: number): unknown[] => Array.isArray(v) && v.length <= max ? v : bad();
const id = (v: unknown, length = 24): string => typeof v === 'string' && new RegExp('^[a-f0-9]{' + length + '}$').test(v) ? v : bad();
const unit = (v: unknown): string => typeof v === 'string' && /^[A-Z]{3}$/.test(v) ? v : bad();
const choice = <T extends string>(v: unknown, values: readonly T[]): T => typeof v === 'string' && values.includes(v as T) ? v as T : bad();
const stamp = (v: unknown): string => { const s = str(v, 50); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,6})?(Z|[+-]\d{2}:\d{2})$/.test(s) || !Number.isFinite(Date.parse(s))) bad(); return s; };
const cents = (v: unknown): string => typeof v === 'string' && v.length < 100 && /^(0|[1-9]\d*|-[1-9]\d*)$/.test(v) ? v : bad();
const nullableCents = (v: unknown) => v === null ? null : cents(v);
const decimal = (v: unknown): string => { const s = str(v, 80); if (!/^(0|[1-9]\d*)(\.\d+)?$/.test(s) || !Number.isFinite(Number(s)) || Number(s) <= 0) bad(); return s; };
export function analysisQuery(query: AnalysisQuery): AnalysisQuery {
  const start = accountDay(query.start), end = accountDay(query.end), days = (Date.parse(end) - Date.parse(start)) / 86400000;
  if (start < '1999-01-04' || days < 1 || days > 365) throw new AccountError('请选择 1999-01-04 起、起点早于终点且不超过 366 天的区间。');
  const accountIds = query.accountIds === 'all' ? 'all' : [...new Set(array(query.accountIds, 300).map(v => id(v)))].sort();
  if (accountIds !== 'all' && !accountIds.length) throw new AccountError('请至少选择一个本人账户。');
  return { start, end, baseCurrency: unit(query.baseCurrency), step: choice(query.step, ['day', 'month']), accountIds };
}
export const analysisReportPath = (query: AnalysisQuery) => { const q = analysisQuery(query); return '/finance-analysis/report?start=' + q.start + '&end=' + q.end + '&baseCurrency=' + q.baseCurrency + '&step=' + q.step + '&accountIds=' + (q.accountIds === 'all' ? 'all' : q.accountIds.join(',')); };
export const analysisFlowsPath = (accountId: string, query: AnalysisQuery, page = 1) => { const q = analysisQuery(query); return '/finance-analysis/accounts/' + id(accountId) + '/cashflows?start=' + q.start + '&end=' + q.end + '&page=' + int(page, 1, 10000) + '&pageSize=50'; };
export const analysisOperationPath = (requestId: string) => '/finance-analysis/operations/' + id(requestId, 32);
export function analysisMoney(value: string | number | null, currency: string): string { if (value === null) return '未能计算'; const n = BigInt(typeof value === 'number' ? int(value, -100_000_000_000_000, 100_000_000_000_000) : cents(value)), a = n < 0n ? -n : n; return unit(currency) + ' ' + (n < 0n ? '−' : '') + (a / 100n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',') + '.' + (a % 100n).toString().padStart(2, '0'); }
export function analysisShare(value: string, total: string): string { const n = BigInt(cents(value)), d = BigInt(cents(total)); if (n < 0n || d <= 0n || n > d) return '比例不可用'; const tenths = (n * 1000n + d / 2n) / d; return (tenths / 10n) + '.' + (tenths % 10n) + '%'; }
export function coverageText(c: Coverage): string { return `已选 ${c.selectedCount} · 已折算 ${c.convertedCount} · 缺估值 ${c.missingValuationCount} · 金额未知 ${c.unknownValuationCount} · 沿用旧估值 ${c.olderValuationCount} · 缺汇率 ${c.missingFxCount}`; }
/** A chart never joins across partial/older valuations or invents zero-valued points. */
export function analysisTrend(series: AnalysisReport['series']) {
  const known = series.filter(p => p.summary.complete && p.summary.coverage.selectedCount > 0), values = known.map(p => BigInt(p.summary.knownNetCents));
  const min = values.length ? values.reduce((a, b) => a < b ? a : b) : null, max = values.length ? values.reduce((a, b) => a > b ? a : b) : null, first = series.length ? Date.parse(series[0].date) : 0, span = series.length ? Date.parse(series[series.length - 1].date) - first : 0;
  const points = series.map(p => ({ date: p.date, x: span ? (Date.parse(p.date) - first) / span : 0, y: p.summary.complete && p.summary.coverage.selectedCount > 0 && min !== null && max !== null ? max === min ? 0.5 : Number((max - BigInt(p.summary.knownNetCents)) * 1_000_000n / (max - min)) / 1_000_000 : null }));
  const segments = points.flatMap((p, i) => i && p.y !== null && points[i - 1].y !== null ? [{ from: points[i - 1], to: p }] : []);
  return { min: min?.toString() ?? null, max: max?.toString() ?? null, points, segments, gapCount: points.filter(p => p.y === null).length };
}
function profile(raw: unknown, accountId: string): Profile { const v = obj(raw); if (v.accountId !== accountId) bad(); return { accountId, revision: int(v.revision), updatedAt: v.updatedAt === null ? null : stamp(v.updatedAt), assetClass: choice(v.assetClass, Object.keys(assetClasses) as Profile['assetClass'][]), liquidity: choice(v.liquidity, Object.keys(liquidityClasses) as Profile['liquidity'][]) }; }
function summary(raw: unknown, selectedCount: number): Summary { const v = obj(raw), c = obj(v.coverage), coverage = Object.fromEntries(['selectedCount', 'knownValuationCount', 'convertedCount', 'missingValuationCount', 'unknownValuationCount', 'olderValuationCount', 'missingFxCount'].map(k => [k, int(c[k], 0, selectedCount)])) as Coverage;
  if (coverage.selectedCount !== selectedCount || coverage.knownValuationCount + coverage.missingValuationCount + coverage.unknownValuationCount !== selectedCount || coverage.convertedCount + coverage.missingFxCount !== coverage.knownValuationCount) bad();
  const result = { knownAssetCents: cents(v.knownAssetCents), knownLiabilityCents: cents(v.knownLiabilityCents), knownNetCents: cents(v.knownNetCents), complete: bool(v.complete), coverage };
  if (BigInt(result.knownAssetCents) < 0n || BigInt(result.knownLiabilityCents) < 0n || BigInt(result.knownAssetCents) - BigInt(result.knownLiabilityCents) !== BigInt(result.knownNetCents) || result.complete && (coverage.convertedCount !== selectedCount || coverage.olderValuationCount)) bad(); return result;
}
function point(raw: unknown, date: string, source: string, target: string): Point { const v = obj(raw); if (v.date !== date) bad(); const valuation = v.valuation === null ? null : readAccountValuation(v.valuation), convertedCents = nullableCents(v.convertedCents); let fx: FxQuote | null = null;
  if (valuation && valuation.asOf > date) bad();
  if (v.fx !== null) { const f = obj(v.fx); if (f.sourceCurrency !== source || f.targetCurrency !== target) bad(); fx = { sourceCurrency: source, targetCurrency: target, sourcePerEur: decimal(f.sourcePerEur), targetPerEur: decimal(f.targetPerEur), rateDate: f.rateDate === null ? null : accountDay(f.rateDate), ageDays: int(f.ageDays, 0, 7), method: choice(f.method, ['identity', 'ecb_cross']), observations: array(f.observations, 2).map(raw => { const o = obj(raw), url = str(o.sourceUrl, 2000); if (!/^https:\/\/(www\.)?ecb\.europa\.eu\//.test(url)) bad(); return { date: accountDay(o.date), currency: unit(o.currency), unitsPerEur: decimal(o.unitsPerEur), version: id(o.version, 64), sourceUrl: url, bodySha256: id(o.bodySha256, 64), fetchedAt: stamp(o.fetchedAt), lastCheckedAt: stamp(o.lastCheckedAt) }; }) };
    if (fx.method === 'identity' ? source !== target || fx.rateDate !== null || fx.observations.length !== 0 || fx.ageDays !== 0 : source === target || fx.rateDate === null || fx.rateDate > date || fx.observations.length < 1 || fx.observations.some(o => o.date !== fx!.rateDate)) bad();
  }
  if (convertedCents !== null && (valuation?.amountCents == null || fx === null || BigInt(convertedCents) < 0n)) bad(); return { date, valuation, convertedCents, fx };
}
function review(raw: unknown): Review { const v = obj(raw); return { revision: int(v.revision), contextDigest: id(v.contextDigest, 64), status: choice(v.status, ['unreviewed', 'current', 'stale']), confirmedAt: v.confirmedAt === null ? null : stamp(v.confirmedAt), cashflowCount: int(v.cashflowCount, 0, 10000), recordedNetFlowCents: cents(v.recordedNetFlowCents), canConfirm: bool(v.canConfirm) }; }
const convertedFields = ['convertedChangeCents', 'convertedNetFlowCents', 'convertedValuationResidualCents', 'fxEffectCents', 'roundingCents'] as const;
function converted(raw: Record<string, unknown>) { return Object.fromEntries(convertedFields.map(k => [k, nullableCents(raw[k])])) as Pick<Change, typeof convertedFields[number]>; }
export function readAnalysisReport(raw: unknown, owner: string, query: AnalysisQuery): AnalysisReport { const q = analysisQuery(query), v = obj(raw); if (v.owner !== owner || v.scope !== 'private_accounts_only' || v.start !== q.start || v.end !== q.end || v.baseCurrency !== q.baseCurrency || v.step !== q.step) bad();
  const accountIds = array(v.accountIds, 300).map(value => id(value)); if (new Set(accountIds).size !== accountIds.length || q.accountIds !== 'all' && [...accountIds].sort().join(',') !== q.accountIds.join(',')) bad();
  const accounts = array(v.accounts, 300).map(raw => { const a = obj(raw), account = readAccount(a.account, owner), c = obj(a.change); return { account, profile: profile(a.profile, account.id), opening: point(a.opening, q.start, account.currency, q.baseCurrency), closing: point(a.closing, q.end, account.currency, q.baseCurrency), review: review(a.review), change: { ...converted(c), originalChangeCents: nullableCents(c.originalChangeCents), recordedNetFlowCents: cents(c.recordedNetFlowCents), valuationResidualCents: nullableCents(c.valuationResidualCents), status: choice(c.status, ['unreviewed', 'stale', 'missing_valuations', 'missing_fx', 'complete'] as const) } }; });
  if (accounts.length !== accountIds.length || new Set(accounts.map(a => a.account.id)).size !== accounts.length || accounts.some(a => !accountIds.includes(a.account.id))) bad();
  const series = array(v.series, 367).map(raw => { const s = obj(raw); return { date: accountDay(s.date), summary: summary(s.summary, accounts.length) }; }); if (!series.length || series[0].date !== q.start || series[series.length - 1].date !== q.end || series.some((s, i) => i > 0 && s.date <= series[i - 1].date)) bad();
  const allocation = array(v.allocation, 7).map(raw => { const b = obj(raw); return { key: choice(b.key, Object.keys(assetClasses) as Profile['assetClass'][]), knownCents: cents(b.knownCents), count: int(b.count, 0, 300) }; }), liquidity = array(v.liquidity, 5).map(raw => { const b = obj(raw); return { key: choice(b.key, Object.keys(liquidityClasses) as Profile['liquidity'][]), knownCents: cents(b.knownCents), count: int(b.count, 0, 300) }; });
  const s = summary(v.summary, accounts.length); for (const buckets of [allocation, liquidity]) if (new Set(buckets.map(b => b.key)).size !== buckets.length || buckets.some(b => BigInt(b.knownCents) < 0n) || buckets.reduce((n, b) => n + BigInt(b.knownCents), 0n) !== BigInt(s.knownAssetCents)) bad();
  const change = obj(v.change); return { owner, scope: 'private_accounts_only', ...q, accountIds, accounts, summary: s, series, allocation, liquidity, change: { ...converted(change), complete: bool(change.complete), reviewedCount: int(change.reviewedCount, 0, accounts.length) } };
}
function cashflow(raw: unknown, accountId: string): Cashflow { const v = obj(raw); if (v.accountId !== accountId) bad(); return { id: id(v.id), accountId, date: accountDay(v.date), direction: choice(v.direction, ['in', 'out']), amountCents: int(v.amountCents, 0, 100_000_000_000_000), note: str(v.note, 1000), revision: int(v.revision, 1), createdAt: stamp(v.createdAt), updatedAt: stamp(v.updatedAt) }; }
export function readAnalysisFlows(raw: unknown, owner: string, accountId: string, query: AnalysisQuery, page: number): Cashflows { const v = obj(raw), q = analysisQuery(query), total = int(v.total, 0, 10000); if (v.owner !== owner || v.accountId !== accountId || v.start !== q.start || v.end !== q.end || v.page !== page || v.pageSize !== 50) bad(); const items = array(v.items, 50).map(f => cashflow(f, accountId)); if (items.length !== Math.min(50, Math.max(0, total - (page - 1) * 50)) || new Set(items.map(f => f.id)).size !== items.length || items.some(f => f.date <= q.start || f.date > q.end)) bad(); return { owner, accountId, start: q.start, end: q.end, items, page, pageSize: 50, total }; }
export function readAnalysisReceipt(raw: unknown, requestId: string, intent?: AnalysisIntent): AnalysisReceipt { const v = obj(raw), operation = choice(v.operation, ['profile', 'cashflow_create', 'cashflow_update', 'cashflow_delete', 'review', 'rates_refresh'] as const), accountId = v.accountId === null ? null : id(v.accountId); if (v.requestId !== id(requestId, 32) || (operation === 'rates_refresh') !== (accountId === null) || intent && (intent.requestId !== requestId || intent.operation !== operation || intent.accountId !== accountId)) bad();
  let result: AnalysisReceipt['result']; const r = obj(v.result);
  if (operation === 'profile') result = profile(r, accountId!); else if (operation === 'review') result = review(r); else if (operation === 'cashflow_delete') { if (r.deleted !== true) bad(); result = { deleted: true, id: id(r.id) }; } else if (operation === 'rates_refresh') result = { inserted: int(r.inserted), updated: int(r.updated), rateCount: int(r.rateCount), retrievedAt: stamp(r.retrievedAt) }; else result = cashflow(r, accountId!);
  return { requestId, operation, accountId, completedAt: stamp(v.completedAt), result, replayed: bool(v.replayed) };
}
export function readAnalysisOperation(raw: unknown, requestId: string): AnalysisReceipt | null { const v = obj(raw); if (v.requestId !== id(requestId, 32)) bad(); if (!bool(v.found)) { if (v.receipt !== null) bad(); return null; } const receipt = readAnalysisReceipt(v.receipt, requestId); if (!receipt.replayed) bad(); return receipt; }
function intent(operation: AnalysisIntent['operation'], accountId: string | null, method: AnalysisIntent['method'], path: string, body: Record<string, unknown>): AnalysisIntent { return { requestId: id(body.requestId, 32), operation, accountId, method, path, body: Object.freeze(body), uncertain: false }; }
export function profileIntent(p: Profile, values: Pick<Profile, 'assetClass' | 'liquidity'>, requestId = newAccountRequestId()): AnalysisIntent { return intent('profile', id(p.accountId), 'PUT', '/finance-analysis/accounts/' + p.accountId + '/profile', { requestId, revision: int(p.revision), assetClass: choice(values.assetClass, Object.keys(assetClasses) as Profile['assetClass'][]), liquidity: choice(values.liquidity, Object.keys(liquidityClasses) as Profile['liquidity'][]) }); }
export function cashflowIntent(account: FinanceAccount, draft: FlowDraft, original: Cashflow | null, requestId = newAccountRequestId()): AnalysisIntent { if (account.archived) throw new AccountError('请先恢复账户，再登记或更改资金进出。'); if (original && original.accountId !== account.id) bad(); const amountCents = parseAccountAmount(draft.amount, false); return intent(original ? 'cashflow_update' : 'cashflow_create', id(account.id), original ? 'PATCH' : 'POST', '/finance-analysis/accounts/' + account.id + '/cashflows' + (original ? '/' + id(original.id) : ''), { requestId, revision: original ? int(original.revision, 1) : 0, date: accountDay(draft.date), direction: choice(draft.direction, ['in', 'out']), amountCents, note: str(draft.note, 1000) }); }
export function deleteCashflowIntent(account: FinanceAccount, flow: Cashflow, requestId = newAccountRequestId()): AnalysisIntent { if (account.archived) throw new AccountError('请先恢复账户，再删除资金进出。'); if (flow.accountId !== account.id) bad(); return intent('cashflow_delete', id(account.id), 'DELETE', '/finance-analysis/accounts/' + account.id + '/cashflows/' + id(flow.id), { requestId, revision: int(flow.revision, 1) }); }
export function reviewIntent(a: AnalysisAccount, query: AnalysisQuery, confirmed: boolean, requestId = newAccountRequestId()): AnalysisIntent { const q = analysisQuery(query); if (!confirmed || !a.review.canConfirm) throw new AccountError('须先核对精确起止日的已知估值，并明确确认期间全部外部资金进出。'); return intent('review', id(a.account.id), 'PUT', '/finance-analysis/accounts/' + a.account.id + '/reviews/' + q.start + '/' + q.end, { requestId, revision: int(a.review.revision), contextDigest: id(a.review.contextDigest, 64), confirmed: true }); }
export function refreshRatesIntent(query: AnalysisQuery, requestId = newAccountRequestId()): AnalysisIntent { const q = analysisQuery(query); return intent('rates_refresh', null, 'POST', '/finance-analysis/rates/refresh', { requestId, start: q.start, end: q.end }); }
export function failedAnalysisIntent(original: AnalysisIntent, error: unknown): AnalysisIntent | null { return !original.uncertain && error instanceof AccountRejected ? null : { ...original, uncertain: true }; }

/** Same no-store, same-origin, bounded streaming and deadline as manual-account transport. */
export async function analysisRequest(path: string, signal: AbortSignal, options: { method?: AnalysisIntent['method'] | 'GET'; payload?: Readonly<Record<string, unknown>>; csrf?: string } = {}): Promise<unknown> {
  const method = options.method || 'GET', read = /^\/finance-analysis\/report\?start=\d{4}-\d{2}-\d{2}&end=\d{4}-\d{2}-\d{2}&baseCurrency=[A-Z]{3}&step=(day|month)&accountIds=(all|[a-f0-9]{24}(,[a-f0-9]{24}){0,299})$/.test(path) || /^\/finance-analysis\/accounts\/[a-f0-9]{24}\/cashflows\?start=\d{4}-\d{2}-\d{2}&end=\d{4}-\d{2}-\d{2}&page=[1-9]\d{0,4}&pageSize=50$/.test(path) || /^\/finance-analysis\/operations\/[a-f0-9]{32}$/.test(path), write = method === 'POST' && (path === '/finance-analysis/rates/refresh' || /^\/finance-analysis\/accounts\/[a-f0-9]{24}\/cashflows$/.test(path)) || method === 'PUT' && /^\/finance-analysis\/accounts\/[a-f0-9]{24}\/(profile|reviews\/\d{4}-\d{2}-\d{2}\/\d{4}-\d{2}-\d{2})$/.test(path) || ['PATCH', 'DELETE'].includes(method) && /^\/finance-analysis\/accounts\/[a-f0-9]{24}\/cashflows\/[a-f0-9]{24}$/.test(path);
  if (method === 'GET' ? !read || options.payload !== undefined : !write || !options.csrf || options.payload === undefined) bad(); const body = options.payload === undefined ? undefined : JSON.stringify(options.payload); if (body && new TextEncoder().encode(body).byteLength > 16384) bad();
  const controller = new AbortController(), deadline = performance.now() + 30000, abort = () => controller.abort(), check = () => { if (signal.aborted) throw new AccountDiscarded(); if (controller.signal.aborted || performance.now() >= deadline) throw new AccountError('连接中断或超时，请核对原操作结果。'); }; if (signal.aborted) throw new AccountDiscarded(); signal.addEventListener('abort', abort, { once: true }); const timer = setTimeout(abort, 30000);
  try { const response = await fetch('/api' + path, { method, credentials: 'same-origin', mode: 'same-origin', cache: 'no-store', redirect: 'error', signal: controller.signal, headers: { Accept: 'application/json', ...(method === 'GET' ? {} : { 'Content-Type': 'application/json', 'X-CSRF-Token': options.csrf! }) }, ...(body === undefined ? {} : { body }) }); check();
    if ([401, 403].includes(response.status)) throw new AccountError('登录或权限已变化，私密内容已隐藏。', response.status); if (response.redirected || !response.headers.get('Content-Type')?.toLowerCase().includes('application/json')) bad(); const reader = response.body?.getReader(); if (!reader) throw new AccountError('分析响应为空，请重新读取。'); let size = 0; const parts: Uint8Array[] = []; try { while (true) { const part = await reader.read(); check(); if (part.done) break; size += part.value.byteLength; if (size > 6_000_000) { controller.abort(); throw new AccountError('分析响应过大，已停止读取。'); } parts.push(part.value); } } finally { void reader.cancel().catch(() => {}); reader.releaseLock(); }
    const bytes = new Uint8Array(size); let offset = 0; for (const part of parts) { bytes.set(part, offset); offset += part.byteLength; } let value: unknown; try { value = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes)); } catch { bad(); } check(); if (!response.ok) { const e = obj(value); throw new AccountError(typeof e.error === 'string' ? str(e.error) : '分析操作未完成，请重新核对。', response.status, typeof e.code === 'string' ? str(e.code, 100) : ''); } return value;
  } catch (e) { check(); if (e instanceof AccountError || e instanceof AccountDiscarded) throw e; throw new AccountError('连接中断，请先核对原操作结果。'); } finally { clearTimeout(timer); signal.removeEventListener('abort', abort); }
}
