/** Owner-only manual accounts. Amounts are original-currency integer cents. */
export type AccountSession = { user: { role: string; householdId?: string; id: string; auth_version?: number } | null; csrf?: string | null };
export type AccountKind = 'asset' | 'liability';
export type AccountStatus = 'active' | 'archived' | 'all';
export type FinanceAccount = { id: string; owner: string; name: string; institution: string; kind: AccountKind; currency: string; note: string; archived: boolean; revision: number; createdAt: string; updatedAt: string; visibility: 'private' };
export type AccountValuation = { asOf: string; amountCents: number | null; source: 'manual'; updatedAt: string };
export type AccountRow = FinanceAccount & { valuation: AccountValuation | null };
export type AccountTotal = { currency: string; assetCount: number; liabilityCount: number; knownCount: number; unknownCount: number; missingCount: number; olderCount: number; knownAssetCents: string; knownLiabilityCents: string; knownNetCents: string };
export type AccountList = { owner: string; asOf: string; status: AccountStatus; scope: 'manual_accounts_only'; accounts: AccountRow[]; totals: AccountTotal[] };
export type AccountHistory = { account: FinanceAccount; valuations: AccountValuation[]; page: number; pageSize: number; total: number };
export type AccountReceipt = { requestId: string; operation: 'create' | 'update' | 'valuation'; accountId: string; completedAt: string; result: { account: FinanceAccount; valuation: AccountValuation | null }; replayed: boolean };
export type AccountIntent = { requestId: string; operation: AccountReceipt['operation']; accountId?: string; method: 'POST' | 'PATCH' | 'PUT'; path: string; body: Readonly<Record<string, unknown>>; uncertain: boolean };
export type AccountDraft = { name: string; institution: string; kind: AccountKind; currency: string; note: string; asOf: string; amount: string; unknown: boolean };
export type AccountEndReview = { requestId: string; identity: string; list: AccountList };
export class AccountError extends Error { status: number; code: string; constructor(message: string, status = 0, code = '') { super(message); this.status = status; this.code = code; } }
export class AccountDiscarded extends Error {}
export class AccountRejected extends AccountError {}
const bad = (): never => { throw new AccountError('账户资料无法完整核对，请重新读取。'); };
const obj = (v: unknown): Record<string, unknown> => v !== null && typeof v === 'object' && !Array.isArray(v) ? v as Record<string, unknown> : bad();
const text = (v: unknown, max: number, required = false, multiline = false): string => {
  if (typeof v !== 'string' || [...v].length > max || required && !v.trim() || [...v].some(c => { const n = c.codePointAt(0)!; return n === 127 || n >= 0xd800 && n <= 0xdfff || n < 32 && !(multiline && (c === '\n' || c === '\t')); })) bad(); return v as string;
};
const integer = (v: unknown, min = 0, max = Number.MAX_SAFE_INTEGER): number => typeof v === 'number' && Number.isSafeInteger(v) && v >= min && v <= max ? v : bad();
const flag = (v: unknown): boolean => typeof v === 'boolean' ? v : bad();
const array = (v: unknown, max: number): unknown[] => Array.isArray(v) && v.length <= max ? v : bad();
const id = (v: unknown, length = 24): string => typeof v === 'string' && new RegExp('^[a-f0-9]{' + length + '}$').test(v) ? v : bad();
const currency = (v: unknown): string => typeof v === 'string' && /^[A-Z]{3}$/.test(v) ? v : bad();
const kind = (v: unknown): AccountKind => v === 'asset' || v === 'liability' ? v : bad();
const status = (v: unknown): AccountStatus => v === 'active' || v === 'archived' || v === 'all' ? v : bad();
const stamp = (v: unknown): string => { const s = text(v, 50); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,6})?(Z|[+-]\d{2}:\d{2})$/.test(s) || !Number.isFinite(Date.parse(s))) bad(); accountDay(s.slice(0, 10)); return s; };
export function accountDay(v: unknown): string { const s = text(v, 10), d = new Date(s + 'T00:00:00Z'); if (!/^(?!0000)\d{4}-\d{2}-\d{2}$/.test(s) || !Number.isFinite(d.getTime()) || d.toISOString().slice(0, 10) !== s) throw new AccountError('请输入有效日期，格式为 YYYY-MM-DD。'); return s; }
const amount = (v: unknown): number | null => v === null ? null : integer(v, 0, 100_000_000_000_000);
const cents = (v: unknown, signed = false): string => { if (typeof v !== 'string' || !(signed ? /^(0|[1-9]\d*|-[1-9]\d*)$/ : /^(0|[1-9]\d*)$/).test(v) || v.length > 19 || BigInt(v) > 30_000_000_000_000_000n || BigInt(v) < -30_000_000_000_000_000n) bad(); return v as string; };
export function formatAccountMoney(v: string | number | null, unit: string): string { currency(unit); if (v === null) return '金额未知'; const raw = typeof v === 'number' ? String(integer(v, -100_000_000_000_000, 100_000_000_000_000)) : cents(v, true), n = BigInt(raw), absolute = n < 0n ? -n : n; return unit + ' ' + (n < 0n ? '−' : '') + (absolute / 100n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',') + '.' + (absolute % 100n).toString().padStart(2, '0'); }
export function parseAccountAmount(value: string, unknown: boolean): number | null { if (unknown) return null; if (value.length > 20 || !/^(0|[1-9]\d*)(\.\d{1,2})?$/.test(value)) throw new AccountError('请填写非负金额，最多两位小数；未知金额请明确选择“金额未知”。'); const [whole, fraction = ''] = value.split('.'), n = BigInt(whole) * 100n + BigInt(fraction.padEnd(2, '0')); if (n > 100_000_000_000_000n) throw new AccountError('金额超过单条估值上限。'); return Number(n); }
export function readAccount(raw: unknown, owner: string): FinanceAccount { const v = obj(raw); if (v.owner !== owner || v.visibility !== 'private') bad(); return { id: id(v.id), owner, name: text(v.name, 120, true), institution: text(v.institution, 120), kind: kind(v.kind), currency: currency(v.currency), note: text(v.note, 1000, false, true), archived: flag(v.archived), revision: integer(v.revision, 1), createdAt: stamp(v.createdAt), updatedAt: stamp(v.updatedAt), visibility: 'private' }; }
export function readAccountValuation(raw: unknown): AccountValuation { const v = obj(raw); if (v.source !== 'manual') bad(); return { asOf: accountDay(v.asOf), amountCents: amount(v.amountCents), source: 'manual', updatedAt: stamp(v.updatedAt) }; }
export function readAccountList(raw: unknown, owner: string, asOf: string, filter: AccountStatus): AccountList {
  const v = obj(raw); if (v.owner !== owner || v.scope !== 'manual_accounts_only' || v.asOf !== accountDay(asOf) || v.status !== status(filter)) bad();
  const accounts = array(v.accounts, 300).map(raw => { const item = obj(raw), account = readAccount(item, owner), valuation = item.valuation === null ? null : readAccountValuation(item.valuation); if (valuation && valuation.asOf > asOf || filter !== 'all' && account.archived !== (filter === 'archived')) bad(); return { ...account, valuation }; });
  if (new Set(accounts.map(a => a.id)).size !== accounts.length) bad();
  const totals = array(v.totals, 300).map(raw => { const t = obj(raw), result: AccountTotal = { currency: currency(t.currency), assetCount: integer(t.assetCount, 0, 300), liabilityCount: integer(t.liabilityCount, 0, 300), knownCount: integer(t.knownCount, 0, 300), unknownCount: integer(t.unknownCount, 0, 300), missingCount: integer(t.missingCount, 0, 300), olderCount: integer(t.olderCount, 0, 300), knownAssetCents: cents(t.knownAssetCents), knownLiabilityCents: cents(t.knownLiabilityCents), knownNetCents: cents(t.knownNetCents, true) };
    const rows = accounts.filter(a => a.currency === result.currency), known = rows.filter(a => a.valuation?.amountCents != null);
    if (result.assetCount !== rows.filter(a => a.kind === 'asset').length || result.liabilityCount !== rows.filter(a => a.kind === 'liability').length || result.knownCount !== known.length || result.unknownCount !== rows.filter(a => a.valuation?.amountCents === null).length || result.missingCount !== rows.filter(a => a.valuation === null).length || result.olderCount !== rows.filter(a => a.valuation && a.valuation.asOf < asOf).length) bad();
    for (const [k, field] of [['asset', 'knownAssetCents'], ['liability', 'knownLiabilityCents']] as const) if (known.filter(a => a.kind === k).reduce((sum, a) => sum + BigInt(a.valuation!.amountCents!), 0n) !== BigInt(result[field])) bad();
    if (BigInt(result.knownAssetCents) - BigInt(result.knownLiabilityCents) !== BigInt(result.knownNetCents)) bad(); return result;
  });
  if (new Set(totals.map(t => t.currency)).size !== totals.length || totals.length !== new Set(accounts.map(a => a.currency)).size || totals.some(t => !accounts.some(a => a.currency === t.currency))) bad(); return { owner, asOf, status: filter, scope: 'manual_accounts_only', accounts, totals };
}
export function readAccountHistory(raw: unknown, owner: string, accountId: string, page: number, pageSize = 50): AccountHistory { const v = obj(raw), account = readAccount(v.account, owner), total = integer(v.total, 0, 3660), valuations = array(v.valuations, pageSize).map(readAccountValuation); if (account.id !== id(accountId) || v.page !== integer(page, 1) || v.pageSize !== integer(pageSize, 1, 100) || valuations.length !== Math.min(pageSize, Math.max(0, total - (page - 1) * pageSize))) bad(); for (let i = 1; i < valuations.length; ++i) if (valuations[i - 1].asOf <= valuations[i].asOf) bad(); return { account, valuations, page, pageSize, total }; }
export function readAccountReceipt(raw: unknown, owner: string, requestId: string, intent?: AccountIntent): AccountReceipt {
  const v = obj(raw), result = obj(v.result), account = readAccount(result.account, owner), valuation = result.valuation === null ? null : readAccountValuation(result.valuation);
  if (v.requestId !== id(requestId, 32) || v.accountId !== account.id || !['create', 'update', 'valuation'].includes(String(v.operation)) || (v.operation === 'update') !== (valuation === null) || intent && (intent.requestId !== requestId || intent.operation !== v.operation || intent.accountId !== undefined && intent.accountId !== account.id)) bad();
  return { requestId, operation: v.operation as AccountReceipt['operation'], accountId: account.id, completedAt: stamp(v.completedAt), result: { account, valuation }, replayed: flag(v.replayed) };
}
export function readAccountOperation(raw: unknown, owner: string, requestId: string): AccountReceipt | null { const v = obj(raw); if (v.requestId !== id(requestId, 32)) bad(); if (!flag(v.found)) { if (v.receipt !== null) bad(); return null; } const receipt = readAccountReceipt(v.receipt, owner, requestId); if (!receipt.replayed) bad(); return receipt; }
/** Call inside a before/after /me fence after a fresh all-accounts read. False alone never unlocks. */
export function accountEndReview(list: AccountList, operation: unknown, owner: string, requestId: string, identity: string): AccountEndReview | null { if (!identity || list.owner !== owner || list.status !== 'all' || readAccountOperation(operation, owner, requestId) !== null) return null; return { requestId, identity, list }; }
export function canEndAccountReview(review: AccountEndReview | null, requestId: string | null, identity: string, confirmed: boolean): boolean { return confirmed === true && !!review && review.requestId === requestId && review.identity === identity; }
export const accountListPath = (asOf: string, filter: AccountStatus) => '/finance-accounts?asOf=' + accountDay(asOf) + '&status=' + status(filter);
export const accountHistoryPath = (accountId: string, page = 1) => '/finance-accounts/' + id(accountId) + '/valuations?page=' + integer(page, 1, 3660) + '&pageSize=50';
export const accountOperationPath = (requestId: string) => '/finance-accounts/operations/' + id(requestId, 32);
export function newAccountRequestId(): string { const bytes = new Uint8Array(16); globalThis.crypto.getRandomValues(bytes); return Array.from(bytes, n => n.toString(16).padStart(2, '0')).join(''); }
function frozenIntent(operation: AccountReceipt['operation'], path: string, method: AccountIntent['method'], body: Record<string, unknown>, accountId?: string): AccountIntent { for (const value of Object.values(body)) if (value && typeof value === 'object') Object.freeze(value); return { requestId: id(body.requestId, 32), operation, path, method, body: Object.freeze(body), accountId, uncertain: false }; }
export function createAccountIntent(draft: AccountDraft, requestId = newAccountRequestId()): AccountIntent { return frozenIntent('create', '/finance-accounts', 'POST', { requestId, revision: 0, name: text(draft.name, 120, true), institution: text(draft.institution, 120), kind: kind(draft.kind), currency: currency(draft.currency), note: text(draft.note, 1000, false, true), valuation: { asOf: accountDay(draft.asOf), amountCents: parseAccountAmount(draft.amount, draft.unknown) } }); }
export function updateAccountIntent(account: FinanceAccount, changes: { name?: string; institution?: string; note?: string; archived?: boolean }, requestId = newAccountRequestId()): AccountIntent { const patch: Record<string, unknown> = {}; if (changes.name !== undefined) patch.name = text(changes.name, 120, true); if (changes.institution !== undefined) patch.institution = text(changes.institution, 120); if (changes.note !== undefined) patch.note = text(changes.note, 1000, false, true); if (changes.archived !== undefined) patch.archived = flag(changes.archived); if (!Object.keys(patch).length || Object.keys(changes).some(k => !['name', 'institution', 'note', 'archived'].includes(k))) bad(); return frozenIntent('update', '/finance-accounts/' + id(account.id), 'PATCH', { requestId, revision: integer(account.revision, 1, Number.MAX_SAFE_INTEGER - 1), changes: patch }, account.id); }
export function valuationAccountIntent(account: FinanceAccount, asOf: string, value: string, unknown: boolean, requestId = newAccountRequestId()): AccountIntent { if (account.archived) throw new AccountError('请先恢复账户，再记录估值。'); return frozenIntent('valuation', '/finance-accounts/' + id(account.id) + '/valuations/' + accountDay(asOf), 'PUT', { requestId, revision: integer(account.revision, 1, Number.MAX_SAFE_INTEGER - 1), amountCents: parseAccountAmount(value, unknown) }, account.id); }
/** An earlier uncertain attempt remains uncertain even if a later retry is rejected. */
export function failedAccountIntent(intent: AccountIntent, error: unknown): AccountIntent | null { return !intent.uncertain && error instanceof AccountRejected ? null : { ...intent, uncertain: true }; }
export const accountSignature = (s: AccountSession) => JSON.stringify([s.user?.role, s.user?.householdId, s.user?.id, s.user?.auth_version, s.csrf]);
export const accountActor = (s: AccountSession): string => s.user?.role === 'member' && s.user.householdId && s.user.id ? JSON.stringify([s.user.householdId, s.user.id]) : bad();
/** Only opaque recovery IDs survive a component or identity replacement. */
export class AccountRecoveryMemory { private values = new Map<string, string>(); get(actor: string) { return this.values.get(actor) || null; } set(actor: string, requestId: string) { this.values.set(actor, id(requestId, 32)); } clear(actor: string, requestId: string) { if (this.values.get(actor) !== requestId) return false; return this.values.delete(actor); } }
export class AccountFence {
  private epoch = 0; private identity: string; constructor(identity: string) { this.identity = identity; } invalidate() { ++this.epoch; }
  async run<T>(me: () => Promise<AccountSession>, job: (csrf: string) => Promise<T>, current: () => boolean): Promise<T> { const epoch = this.epoch; const check = (s: AccountSession) => { if (!current() || epoch !== this.epoch) throw new AccountDiscarded(); if (!s || s.user?.role !== 'member' || !s.user.id || !s.user.householdId || !Number.isSafeInteger(s.user.auth_version) || Number(s.user.auth_version) < 1 || typeof s.csrf !== 'string' || !s.csrf || accountSignature(s) !== this.identity) throw new AccountDiscarded('identity'); return s.csrf; }; const csrf = check(await me()); let result!: T, error: unknown, failed = false; try { result = await job(csrf); } catch (e) { error = e; failed = true; } check(await me()); if (failed) throw error; return result; }
}
export async function checkedAccountWrite<T>(guard: (job: (csrf: string) => Promise<T>) => Promise<T>, write: (csrf: string) => Promise<T>): Promise<T> { return guard(async csrf => { try { return await write(csrf); } catch (e) { if (e instanceof AccountError && [400, 404, 409, 413, 429].includes(e.status)) throw new AccountRejected(e.message, e.status, e.code); throw e; } }); }
export async function accountRequest(path: string, signal: AbortSignal, options: { method?: 'GET' | 'POST' | 'PATCH' | 'PUT'; payload?: Readonly<Record<string, unknown>>; csrf?: string } = {}): Promise<unknown> {
  const method = options.method || 'GET', read = path === '/me' || /^\/finance-accounts\?asOf=\d{4}-\d{2}-\d{2}&status=(active|archived|all)$/.test(path) || /^\/finance-accounts\/[a-f0-9]{24}\/valuations\?page=[1-9]\d{0,3}&pageSize=50$/.test(path) || /^\/finance-accounts\/operations\/[a-f0-9]{32}$/.test(path), write = method === 'POST' && path === '/finance-accounts' || method === 'PATCH' && /^\/finance-accounts\/[a-f0-9]{24}$/.test(path) || method === 'PUT' && /^\/finance-accounts\/[a-f0-9]{24}\/valuations\/\d{4}-\d{2}-\d{2}$/.test(path);
  if (method === 'GET' ? !read || options.payload !== undefined : !write || !options.csrf || options.payload === undefined) bad(); const body = options.payload === undefined ? undefined : JSON.stringify(options.payload); if (body && new TextEncoder().encode(body).byteLength > 16_384) throw new AccountError('账户文字过长，请缩短后重试。');
  const controller = new AbortController(), deadline = performance.now() + 30_000, abort = () => controller.abort(); const check = () => { if (signal.aborted) throw new AccountDiscarded(); if (controller.signal.aborted || performance.now() >= deadline) throw new AccountError('连接中断或超时，请核对操作结果。'); }; if (signal.aborted) throw new AccountDiscarded(); signal.addEventListener('abort', abort, { once: true }); const timer = setTimeout(abort, 30_000);
  try { const response = await fetch('/api' + path, { method, credentials: 'same-origin', mode: 'same-origin', cache: 'no-store', redirect: 'error', signal: controller.signal, headers: { Accept: 'application/json', ...(method === 'GET' ? {} : { 'Content-Type': 'application/json', 'X-CSRF-Token': options.csrf! }) }, ...(body === undefined ? {} : { body }) }); check();
    if ([401, 403].includes(response.status)) throw new AccountError('登录或权限已变化，账户内容已隐藏。', response.status); if (response.redirected || !response.headers.get('Content-Type')?.toLowerCase().includes('application/json')) throw new AccountError('账户服务未返回可核对的 JSON。'); const reader = response.body?.getReader(); if (!reader) throw new AccountError('账户响应为空，请重新读取。'); let size = 0; const parts: Uint8Array[] = []; try { while (true) { const part = await reader.read(); check(); if (part.done) break; size += part.value.byteLength; if (size > 2_000_000) { controller.abort(); throw new AccountError('账户响应过大，已停止读取。'); } parts.push(part.value); } } finally { void reader.cancel().catch(() => {}); reader.releaseLock(); }
    const bytes = new Uint8Array(size); let offset = 0; for (const part of parts) { bytes.set(part, offset); offset += part.byteLength; } let value: unknown; try { value = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes)); } catch { bad(); } check(); if (!response.ok) { const e = obj(value); throw new AccountError(typeof e.error === 'string' ? text(e.error, 2000) : '账户操作未完成，请核对当前状态。', response.status, typeof e.code === 'string' ? text(e.code, 100) : ''); } return value;
  } catch (e) { check(); if (e instanceof AccountError || e instanceof AccountDiscarded) throw e; throw new AccountError('连接中断，请先核对操作结果。'); } finally { clearTimeout(timer); signal.removeEventListener('abort', abort); }
}
